// /lib/mock-data.ts
import { Course, Job, Resource } from "./types";

export const courses: Course[] = [
  {
    id: 1,
    title: "The Complete JavaScript Course 2024: From Zero to Expert!",
    platform: "Udemy",
    instructor: "Jonas Schmedtmann",
    rating: 4.8,
    students: 550000,
    duration: "21 hours",
    level: "Beginner",
    category: "Programming",
    tags: ["JavaScript", "Web Development", "Frontend"],
    price: "Free",
    originalPrice: "$84.99",
    expiryDate: "2024-09-15",
    image: "/placeholder.svg?height=200&width=300",
    description:
      "Master JavaScript with projects, challenges and theory. Many courses in one! The only JS course you need.",
    isPopular: true,
  },
  {
    id: 2,
    title: "Python for Data Science and Machine Learning Bootcamp",
    platform: "Udemy",
    instructor: "Jose Portilla",
    rating: 4.7,
    students: 450000,
    duration: "25 hours",
    level: "Intermediate",
    category: "Data Science",
    tags: ["Python", "Machine Learning", "Data Science"],
    price: "Free",
    originalPrice: "$129.99",
    expiryDate: "2024-09-10",
    image: "/placeholder.svg?height=200&width=300",
    description:
      "Learn how to use Python for Data Science and Machine Learning with real projects.",
    isTrending: true,
  },
  {
    id: 3,
    title: "AWS Certified Solutions Architect - Associate 2024",
    platform: "Udemy",
    instructor: "Stephane Maarek",
    rating: 4.8,
    students: 320000,
    duration: "27 hours",
    level: "Advanced",
    category: "Cloud Computing",
    tags: ["AWS", "Cloud", "Certification"],
    price: "Free",
    originalPrice: "$94.99",
    expiryDate: null,
    image: "/placeholder.svg?height=200&width=300",
    description:
      "Pass the AWS Certified Solutions Architect Associate Exam with this comprehensive course.",
    isNew: true,
  },
  {
    id: 4,
    title: "React - The Complete Guide 2024 (incl. React Router & Redux)",
    platform: "Udemy",
    instructor: "Maximilian Schwarzmüller",
    rating: 4.8,
    students: 720000,
    duration: "48 hours",
    level: "Intermediate",
    category: "Web Development",
    tags: ["React", "JavaScript", "Frontend"],
    price: "Free",
    originalPrice: "$129.99",
    expiryDate: "2024-09-20",
    image: "/placeholder.svg?height=200&width=300",
    description:
      "Dive deep into React, React Router, and Redux. Build complex and high-performance apps.",
  },
  {
    id: 5,
    title: "Complete SQL Bootcamp 2024: Go from Zero to Hero",
    platform: "Udemy",
    instructor: "Jose Portilla",
    rating: 4.7,
    students: 620000,
    duration: "9 hours",
    level: "Beginner",
    category: "Database",
    tags: ["SQL", "Database", "PostgreSQL"],
    price: "Free",
    originalPrice: "$84.99",
    expiryDate: null,
    image: "/placeholder.svg?height=200&width=300",
    description:
      "Learn how to use SQL quickly and effectively with this course for beginners.",
  },
];

export const jobs: Job[] = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechCorp",
    location: "Lagos, Nigeria",
    type: "Full-time",
    workMode: "Remote",
    experience: "2+ years",
    salary: "₦300,000 - ₦500,000",
    salaryType: "monthly",
    description:
      "We are looking for a skilled frontend developer to join our team and work on exciting projects.",
    requirements: [
      "Proficient in React.js",
      "Strong CSS skills",
      "Experience with TypeScript",
    ],
    benefits: ["Health insurance", "Paid time off", "Flexible hours"],
    postedDate: "2024-08-01",
    platform: "LinkedIn",
    companyLogo: "/placeholder.svg?height=50&width=50",
    featured: true,
  },
  {
    id: 2,
    title: "Data Analyst",
    company: "Data Insights Ltd.",
    location: "Abuja, Nigeria",
    type: "Contract",
    workMode: "Hybrid",
    experience: "1+ years",
    salary: "₦200,000 - ₦250,000",
    salaryType: "monthly",
    description:
      "Analyze and interpret complex datasets to help drive strategic decisions.",
    requirements: ["SQL", "Excel", "Data Visualization tools"],
    benefits: ["Remote days", "Training allowance"],
    postedDate: "2024-08-05",
    platform: "Indeed",
    companyLogo: "/placeholder.svg?height=50&width=50",
    urgent: true,
  },
  {
    id: 3,
    title: "Backend Developer",
    company: "SoftSolutions",
    location: "Remote",
    type: "Full-time",
    workMode: "Remote",
    experience: "3+ years",
    salary: "$3,000 - $4,500",
    salaryType: "monthly",
    description:
      "Design and implement backend services using Node.js and Express.",
    requirements: ["Node.js", "MongoDB", "REST APIs"],
    benefits: ["Flexible hours", "Annual retreat"],
    postedDate: "2024-07-28",
    platform: "WeWorkRemotely",
    companyLogo: "/placeholder.svg?height=50&width=50",
  },
];

export const resources: Resource[] = [
  {
    id: 1,
    title: "MDN Web Docs",
    description: "Comprehensive resource for web developers, by Mozilla.",
    category: "Web Development",
    type: "Website",
    url: "https://developer.mozilla.org",
    tags: ["HTML", "CSS", "JavaScript"],
    rating: 5,
    featured: true,
    dateAdded: "2024-08-01",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 2,
    title: "Figma",
    description: "Collaborative interface design tool.",
    category: "Design",
    type: "Tool",
    url: "https://figma.com",
    tags: ["UI", "UX", "Prototyping"],
    rating: 4.8,
    dateAdded: "2024-08-03",
    image: "/placeholder.svg?height=200&width=300",
  },
  {
    id: 3,
    title: "Python Cheat Sheet",
    description: "Quick reference PDF for Python basics.",
    category: "Programming",
    type: "PDF",
    url: "https://example.com/python-cheatsheet.pdf",
    tags: ["Python", "Cheatsheet", "Beginner"],
    rating: 4.5,
    dateAdded: "2024-08-05",
    image: "/placeholder.svg?height=200&width=300",
  },
];
